version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: DockerFile
    volumes:
      - ..:/workspace:cached
      - ~/.gitconfig:/root/.gitconfig:cached
      - ~/.git-credentials:/root/.git-credentials:cached
    ports:
      - "3001:3001"
    command: bash -c "pnpm dev"
