env:
  ACTIONS_STEP_DEBUG: true
name: Deploy AboutMeSite to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Debug root directory
        run: ls -la

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Debug app/AboutMeSite directory
        run: ls -la app/AboutMeSite

      - name: Install dependencies
        working-directory: app/AboutMeSite
        run: bun install

      - name: Inject static export config (temp)
        working-directory: app/AboutMeSite
        run: |
          echo "module.exports = { output: 'export', trailingSlash: true };" > next.config.js

      - name: Debug after injecting next.config.js
        run: ls -la app/AboutMeSite

      - name: Build and export
        working-directory: app/AboutMeSite
        run: |
          bun run build
          bunx next export

      - name: Debug after build and export
        run: ls -la app/AboutMeSite/out

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: app/AboutMeSite/out

      - name: Restore next.config.js
        working-directory: app/AboutMeSite
        run: git restore next.config.js

      - name: Debug package.json
        working-directory: app/AboutMeSite
        run: cat package.json
      - name: Debug next.config.js
        working-directory: app/AboutMeSite
        run: cat next.config.js

      - name: Debug output directory
        run: ls -la app/AboutMeSite/out