name: Deploy AboutMeSite to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Debug root directory
        run: ls -la

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Debug AboutMeSite directory
        run: ls -la AboutMeSite

      - name: Install dependencies
        working-directory: AboutMeSite
        run: bun install

      - name: Inject static export config (temp)
        working-directory: AboutMeSite
        run: |
          echo "module.exports = { output: 'export', trailingSlash: true };" > next.config.cjs

      - name: Debug after injecting next.config.cjs
        run: ls -la AboutMeSite

      - name: Build
        working-directory: AboutMeSite
        run: bun run build

      - name: Debug directory structure after build
        run: ls -la AboutMeSite

      - name: Debug output directory
        run: ls -la AboutMeSite/out

      - name: List all files in AboutMeSite
        run: find AboutMeSite

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: AboutMeSite/out

      - name: Restore next.config.cjs
        working-directory: AboutMeSite
        run: git restore next.config.cjs