name: Deploy AboutMeSite to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Debug root directory
        run: ls -la

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Debug root directory
        run: ls -la

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Debug project directory
        run: ls -la

      - name: Install dependencies
        run: bun install

      - name: Inject improved static export config
        run: |
          echo "module.exports = {
            output: 'export',
            distDir: 'out',
            trailingSlash: true,
            images: {
              unoptimized: true
            }
          };" > next.config.cjs
          cat next.config.cjs

      - name: Debug after injecting next.config.cjs
        run: ls -la

      - name: Build
        run: bun run build

      - name: Debug directory structure after build
        run: |
          echo "Current directory structure:"
          ls -la
          echo "Next.js build directory:"
          ls -la .next || echo "No .next directory found"
          echo "Checking for out directory in different locations:"
          ls -la out || echo "No out directory found"
          ls -la .next/out || echo "No .next/out directory found"

      - name: Export manually if needed
        run: |
          if [ ! -d "out" ]; then
            echo "No out directory found, trying to create it manually"
            mkdir -p out
            if [ -d ".next/standalone" ]; then
              cp -r .next/standalone/* out/
            fi
            if [ -d ".next/static" ]; then
              cp -r .next/static out/
            fi
          fi
          ls -la out || echo "Still no out directory"

      - name: Check package.json scripts
        run: cat package.json

      - name: List all files in project
        run: find . -type f | grep -v "node_modules" | sort

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out
